/**
 * @fileoverview Adventure Land MMORPG ESLint plugin adding a custom environment containing global
 * game functions, classes, and variables.
 * @author David Timmons
 */
'use strict';

//------------------------------------------------------------------------------
// Plugin Definition
//------------------------------------------------------------------------------

module.exports = {
    environments: {
        api: {
            globals: {
                accept_party_invite: false,
                accept_party_request: false,
                activate: false,
                add_bottom_button: false,
                add_top_button: false,
                attack: false,
                auto_reload: false,
                bank_deposit: false,
                bank_store: false,
                bank_withdraw: false,
                bfs: false,
                buy_with_gold: false,
                buy_with_shells: false,
                buy: false,
                can_attack: false,
                can_heal: false,
                can_move_to: false,
                can_use: false,
                change_server: false,
                change_target: false,
                clear_buttons: false,
                clear_drawings: false,
                code_draw: false,
                command_character: false,
                compound: false,
                continue_pathfinding: false,
                craft: false,
                cruise: false,
                destroy_item: false,
                draw_circle: false,
                draw_line: false,
                equip: false,
                eval_s: false,
                exchange: false,
                game_log: false,
                get_active_characters: false,
                get_map: false,
                get_nearest_hostile: false,
                get_nearest_monster: false,
                get_player: false,
                get_socket: false,
                get_target_of: false,
                get_target: false,
                get_targeted_monster: false,
                handle_command: true,
                handle_death: true,
                heal: false,
                in_attack_range: false,
                is_character: false,
                is_monster: false,
                is_moving: false,
                is_npc: false,
                is_paused: false,
                is_player: false,
                is_pvp: false,
                is_transporting: false,
                item_grade: false,
                item_properties: false,
                item_value: false,
                load_code: false,
                loot: false,
                map_key: false,
                move: false,
                on_cm: true,
                on_combined_damage: true,
                on_destroy: false,
                on_disappear: true,
                on_draw: true,
                on_game_event: true,
                on_party_invite: true,
                on_party_request: true,
                pause: false,
                performance_trick: false,
                pget: false,
                plot: false,
                pm: false,
                preview_item: false,
                proxy: false,
                pset: false,
                qpush: false,
                quantity: false,
                reset_mappings: false,
                respawn: false,
                say: false,
                sell: false,
                send_cm: false,
                send_gold: false,
                send_item: false,
                send_party_invite: false,
                send_party_request: false,
                set_button_color: false,
                set_button_onclick: false,
                set_button_value: false,
                set_keymap: false,
                set_message: false,
                set_skillbar: false,
                shift: false,
                show_json: false,
                smart_move_logic: false,
                smart_move: false,
                smooth_path: false,
                start_character: false,
                start_pathfinding: false,
                stop_character: false,
                stop: false,
                swap: false,
                trade_buy: false,
                trade: false,
                transport: false,
                trigger_event: false,
                unequip: false,
                unfriend: false,
                unmap_key: false,
                upgrade: false,
                use_hp_or_mp: false,
                use_skill: false,
                use: false,
                xmove: false,
            },
        },
    },
};
